local M = {}
local status, icons = pcall(require, "nvim-web-devicons")

if not status then
	M.Config = function()
		vim.notify("icon is not found ...", vim.log.levels.ERROR, { title = "Nvim" })
	end
	return M
end

function M.Config()
	icons.setup({
		override = {
			c = { icon = "", color = "#ccf4ff", name = "C" },
			cpp = { icon = "", color = "#ccf4ff", name = "Cpp" },
			cs = { icon = "", color = "#ccf4ff", name = "CSharp" },
			py = { icon = "", color = "#ffebcc", name = "Python" },
			js = { icon = "", color = "#ffebcc", name = "Js" },
			ts = { icon = "", color = "#ccf4ff", name = "Ts" },
			jsx = { icon = "", color = "#ffebcc", name = "Jsx" },
			tsx = { icon = "", color = "#ccf4ff", name = "Tsx" },
			java = { icon = "󰬷", color = "#ffebcc", name = "Java" },
			go = { icon = "", color = "#ccf4ff", name = "Go" },
			rs = { icon = "", color = "#ffebcc", name = "Rust" },
			dart = { icon = "", color = "#ccd0ff", name = "Dart" },
			lua = { icon = "󱨇", color = "#ffebcc", name = "Lua" },
			vim = { icon = "", color = "#ddffcc", name = "Vim" },
			sh = { icon = "", color = "#ffebcc", name = "Sh" },
			bash = { icon = "", color = "#ffebcc", name = "Bash" },
			html = { icon = "", color = "#ccd0ff", name = "Html" },
			css = { icon = "", color = "#ffcbcb", name = "Css" },
			scss = { icon = "", color = "#ffcbcb", name = "Scss" },
			less = { icon = "󰅯", color = "#ffcbcb", name = "Less" },
			vue = { icon = "", color = "#ddffcc", name = "Vue" },
			svg = { icon = "", color = "#ccffeb", name = "Svg" },
			jade = { icon = "", color = "#ccd0ff", name = "Jade" },
			json = { icon = "󰘦", color = "#ffebcc", name = "Json" },
			yaml = { icon = "", color = "#ffcbcb", name = "Yaml" },
			xml = { icon = "", color = "#ffcbcb", name = "Xml" },
			toml = { icon = "󰰥", color = "#ffebcc", name = "Toml" },
			csv = { icon = "", color = "#ccf4ff", name = "Csv" },
			md = { icon = "󰯃", color = "#ffebcc", name = "Markdown" },
			txt = { icon = "󱩼", color = "#ccd0ff", name = "Txt" },
			doc = { icon = "", color = "#ccf4ff", name = "Doc" },
			docx = { icon = "", color = "#ccf4ff", name = "Docx" },
			xls = { icon = "", color = "#ddffcc", name = "Xls" },
			xlsx = { icon = "", color = "#ddffcc", name = "Xlsx" },
			png = { icon = "󰸭", color = "#ccffeb", name = "Png" },
			jpg = { icon = "󰈥", color = "#ccffeb", name = "Jpg" },
			jpeg = { icon = "󰈥", color = "#ccffeb", name = "Jpeg" },
			gif = { icon = "󰵸", color = "#ccffeb", name = "Gif" },
			webp = { icon = "󰜫", color = "#ccffeb", name = "Webp" },
			avif = { icon = "󰬈", color = "#ccffeb", name = "Avif" },
			mp3 = { icon = "󰈣", color = "#ccffeb", name = "Mp3" },
			mp4 = { icon = "󰁧", color = "#ccffeb", name = "Mp4" },
			mov = { icon = "󰿎", color = "#ccffeb", name = "Mov" },
			ttf = { icon = "", color = "#ffcbcb", name = "Ttf" },
			woff = { icon = "", color = "#ffcbcb", name = "Woff" },
			zip = { icon = "", color = "#ccd0ff", name = "Zip" },
			out = { icon = "", color = "#ffcbcb", name = "Cout" },
			class = { icon = "", color = "#ccd0ff", name = "Class" },
			so = { icon = "", color = "#ccd0ff", name = "So" },
			dat = { icon = "󱎔", color = "#ffcbcb", name = "Dat" },
			log = { icon = "", color = "#ccf4ff", name = "Log" },
			conf = { icon = "", color = "#ccd0ff", name = "Config" },
			http = { icon = "󰭄", color = "#ffcbcb", name = "Http" },
			npmrc = { icon = "", color = "#ccf4ff", name = "Npmrc" },
			snippets = { icon = "", color = "#ccd0ff", name = "Snippets" },
		},
		override_by_filename = {
			["readme.md"] = { icon = "󰯃", color = "#ffebcc", name = "Markdown" },
			["tsconfig.json"] = { icon = "", color = "#ffcbcb", name = "TsConfig" },
			["commitlint.config.js"] = { icon = "󰜘", color = "#ffcbcb", name = "Commitlint" },
			["tailwind.config.js"] = { icon = "󱏿", color = "#ffcbcb", name = "Tailwind" },
			["go.mod"] = { icon = "", color = "#ccf4ff", name = "GoMod" },
			["go.sum"] = { icon = "󰞆", color = "#ffcbcb", name = "GoSum" },
			["init.lua"] = { icon = "󱤁", color = "#ccd0ff", name = "Init" },
			["package.json"] = { icon = "󰏔", color = "#ccf4ff", name = "Package" },
			["commands.lua"] = { icon = "󰇄", color = "#ccd0ff", name = "AutoCommands" },
			["custom.lua"] = { icon = "󰬎", color = "#ccd0ff", name = "GlobalSettings" },
			["keymaps.lua"] = { icon = "󰌌", color = "#ccd0ff", name = "keyMaps" },
			["www"] = { icon = "󰇧", color = "#ffebcc", name = "Network" },
			["LICENSE"] = { icon = "", color = "#ffebcc", name = "LICENSE" },
			["server.js"] = { icon = "󰒋", color = "#ccd0ff", name = "Server" },
			["tags"] = { icon = "", color = "#ccd0ff", name = "Tag" },
		},
		override_by_extension = {
			["d.ts"] = { icon = "", color = "#ccf4ff", name = "TypeScriptDeclaration" },
			["ico"] = { icon = "󱞈", color = "#ccf4ff", name = "Favicon" },
			["lock"] = { icon = "󰦝", color = "#ffcbcb", name = "Lock" },
			["lockb"] = { icon = "󰦝", color = "#ffcbcb", name = "LockBinary" },
			["db"] = { icon = "󰆼", color = "#ccf4ff", name = "Database" },
			["sql"] = { icon = "󰆼", color = "#ccf4ff", name = "Sql" },
			["sqlite"] = { icon = "󰆼", color = "#ccf4ff", name = "Sqlite" },
			["test"] = { icon = "", color = "#ddffcc", name = "Test" },
			["spec"] = { icon = "", color = "#ddffcc", name = "Spec" },
			["makefile"] = { icon = "", color = "#ffebcc", name = "Makefile" },
			["cmake"] = { icon = "", color = "#ffebcc", name = "Cmake" },
			["dockerfile"] = { icon = "󰡨", color = "#ccf4ff", name = "Dockerfile" },
			["dockerignore"] = { icon = "󰡨", color = "#ffcbcb", name = "DockerIgnore" },
			["git"] = { icon = "󰊢", color = "#ffebcc", name = "Git" },
			["gitignore"] = { icon = "", color = "#ffcbcb", name = "GitIgnore" },
			["zsh"] = { icon = "󰬡", color = "#ccf4ff", name = "Zsh" },
			["zshrc"] = { icon = "󰬡", color = "#ccf4ff", name = "Zshrc" },
			["fish"] = { icon = "󰈺", color = "#ffcbcb", name = "Fish" },
			["ini"] = { icon = "󰒓", color = "#ffcbcb", name = "Ini" },
			["cfg"] = { icon = "󰒓", color = "#ffcbcb", name = "Config" },
			["properties"] = { icon = "", color = "#ffcbcb", name = "Properties" },
			["pdf"] = { icon = "󰈦", color = "#ffcbcb", name = "Pdf" },
			["epub"] = { icon = "󰦜", color = "#ccd0ff", name = "Epub" },
			["bak"] = { icon = "󰁯", color = "#ccd0ff", name = "Backup" },
			["tmp"] = { icon = "", color = "#ccd0ff", name = "Temp" },
			["swp"] = { icon = "󰓢", color = "#ccd0ff", name = "Swap" },
			["h"] = { icon = "󰙲", color = "#ccf4ff", name = "Header" },
			["hpp"] = { icon = "󰙲", color = "#ccf4ff", name = "HeaderPlus" },
			["rb"] = { icon = "󰴭", color = "#ffcbcb", name = "Ruby" },
			["ejs"] = { icon = "", color = "#ffebcc", name = "EJS" },
			["pug"] = { icon = "󰚧", color = "#ccd0ff", name = "Pug" },
			["gql"] = { icon = "", color = "#ffcbcb", name = "GraphQL" },
			["rc"] = { icon = "󰒓", color = "#ffcbcb", name = "RC" },
			["eslintrc"] = { icon = "", color = "#ffcbcb", name = "ESLintRC" },
			["prettierrc"] = { icon = "", color = "#ffcbcb", name = "PrettierRC" },
			["babelrc"] = { icon = "󰨥", color = "#ffcbcb", name = "BabelRC" },
			["webpack"] = { icon = "󰜫", color = "#ccf4ff", name = "Webpack" },
			["vite"] = { icon = "", color = "#ccf4ff", name = "Vite" },
			["jest"] = { icon = "", color = "#ddffcc", name = "Jest" },
			["exe"] = { icon = "󰨊", color = "#ffcbcb", name = "EXE" },
			["dll"] = { icon = "", color = "#ffcbcb", name = "DLL" },
			["dylib"] = { icon = "󰪃", color = "#ffcbcb", name = "DYLIB" },
			["bin"] = { icon = "", color = "#ffcbcb", name = "BIN" },
			["app"] = { icon = "", color = "#ffcbcb", name = "APP" },
			["diff"] = { icon = "", color = "#ccf4ff", name = "Diff" },
			["patch"] = { icon = "", color = "#ccf4ff", name = "Patch" },
		},
	})
end

return M
