local status, mini_icons = pcall(require, "mini.icons")
local M = {}

if not status then
	function M.Config()
		vim.notify("mini.icons is not found ...", vim.log.levels.ERROR, { title = "Nvim" })
	end
	return M
end

function M.Config()
	mini_icons.setup({
		style = "glyph",
		default = {
			file = {
				glyph = "󰈚",
				hl = "MiniIconsPurple",
			},
		},
		extension = {
			["d.ts"] = { glyph = "", hl = "MiniIconsAzure" },
			pdf = { glyph = "󰈦", hl = "MiniIconsRed" },
			epub = { glyph = "󰦜", hl = "MiniIconsPurple" },
			png = { glyph = "󰸭", hl = "MiniIconsCyan" },
			jpg = { glyph = "󰈥", hl = "MiniIconsCyan" },
			jpeg = { glyph = "󰈥", hl = "MiniIconsCyan" },
			gif = { glyph = "󰵸", hl = "MiniIconsCyan" },
			webp = { glyph = "󰜫", hl = "MiniIconsCyan" },
			avif = { glyph = "󰬈", hl = "MiniIconsCyan" },
			ico = { glyph = "󱞈", hl = "MiniIconsAzure" },
			svg = { glyph = "", hl = "MiniIconsCyan" },
			mp3 = { glyph = "󰈣", hl = "MiniIconsCyan" },
			mp4 = { glyph = "󰁧", hl = "MiniIconsCyan" },
			mov = { glyph = "󰿎", hl = "MiniIconsCyan" },
			ttf = { glyph = "", hl = "MiniIconsRed" },
			woff = { glyph = "", hl = "MiniIconsRed" },
			zip = { glyph = "󰛫", hl = "MiniIconsPurple" },
			out = { glyph = "", hl = "MiniIconsRed" },
			class = { glyph = "", hl = "MiniIconsPurple" },
			so = { glyph = "", hl = "MiniIconsPurple" },
			dll = { glyph = "", hl = "MiniIconsRed" },
			dylib = { glyph = "󰪃", hl = "MiniIconsRed" },
			exe = { glyph = "󰨊", hl = "MiniIconsRed" },
			bin = { glyph = "", hl = "MiniIconsRed" },
			app = { glyph = "", hl = "MiniIconsRed" },
			conf = { glyph = "", hl = "MiniIconsPurple" },
			ini = { glyph = "󰒓", hl = "MiniIconsRed" },
			cfg = { glyph = "󰒓", hl = "MiniIconsRed" },
			rc = { glyph = "󰒓", hl = "MiniIconsRed" },
			properties = { glyph = "", hl = "MiniIconsRed" },
			lock = { glyph = "󰦝", hl = "MiniIconsRed" },
			lockb = { glyph = "󰦝", hl = "MiniIconsRed" },
			test = { glyph = "", hl = "MiniIconsGreen" },
			spec = { glyph = "", hl = "MiniIconsGreen" },
			dockerignore = { glyph = "󰡨", hl = "MiniIconsRed" },
			dat = { glyph = "󱎔", hl = "MiniIconsRed" },
			log = { glyph = "", hl = "MiniIconsAzure" },
			bak = { glyph = "󰁯", hl = "MiniIconsPurple" },
			tmp = { glyph = "", hl = "MiniIconsPurple" },
			swp = { glyph = "󰓢", hl = "MiniIconsPurple" },
			snippets = { glyph = "", hl = "MiniIconsPurple" },
			sqlite = { glyph = "󰆼", hl = "MiniIconsAzure" },
		},
		file = {
			["README.md"] = { glyph = "", hl = "MiniIconsOrange" },
			["tsconfig.json"] = { glyph = "", hl = "MiniIconsRed" },
			["commitlint.config.js"] = { glyph = "󰜘", hl = "MiniIconsRed" },
			["tailwind.config.js"] = { glyph = "󱏿", hl = "MiniIconsRed" },
			["go.mod"] = { glyph = "", hl = "MiniIconsAzure" },
			["go.sum"] = { glyph = "󰞆", hl = "MiniIconsRed" },
			["init.lua"] = { glyph = "󱤁", hl = "MiniIconsPurple" },
			["package.json"] = { glyph = "󰏔", hl = "MiniIconsAzure" },
			["commands.lua"] = { glyph = "󰇄", hl = "MiniIconsPurple" },
			["custom.lua"] = { glyph = "󰬎", hl = "MiniIconsPurple" },
			["keymaps.lua"] = { glyph = "󰌌", hl = "MiniIconsPurple" },
			["pkg-manager.lua"] = { glyph = "󱑢", hl = "MiniIconsPurple" },
			["www"] = { glyph = "󰇧", hl = "MiniIconsOrange" },
			["LICENSE"] = { glyph = "", hl = "MiniIconsOrange" },
			["server.js"] = { glyph = "󰒋", hl = "MiniIconsPurple" },
			["tags"] = { glyph = "", hl = "MiniIconsPurple" },
		},
		filetype = {
			c = { glyph = "", hl = "MiniIconsAzure" },
			cpp = { glyph = "", hl = "MiniIconsAzure" },
			cs = { glyph = "", hl = "MiniIconsAzure" },
			python = { glyph = "", hl = "MiniIconsOrange" },
			javascript = { glyph = "", hl = "MiniIconsOrange" },
			typescript = { glyph = "", hl = "MiniIconsAzure" },
			javascriptreact = { glyph = "", hl = "MiniIconsOrange" },
			typescriptreact = { glyph = "", hl = "MiniIconsAzure" },
			java = { glyph = "󰬷", hl = "MiniIconsOrange" },
			go = { glyph = "", hl = "MiniIconsAzure" },
			rust = { glyph = "", hl = "MiniIconsOrange" },
			dart = { glyph = "", hl = "MiniIconsPurple" },
			lua = { glyph = "󱨇", hl = "MiniIconsOrange" },
			vim = { glyph = "", hl = "MiniIconsGreen" },
			ruby = { glyph = "󰴭", hl = "MiniIconsRed" },
			sh = { glyph = "", hl = "MiniIconsOrange" },
			bash = { glyph = "", hl = "MiniIconsOrange" },
			zsh = { glyph = "󰬡", hl = "MiniIconsAzure" },
			fish = { glyph = "󰈺", hl = "MiniIconsRed" },
			html = { glyph = "", hl = "MiniIconsPurple" },
			css = { glyph = "", hl = "MiniIconsRed" },
			scss = { glyph = "", hl = "MiniIconsRed" },
			less = { glyph = "󰅯", hl = "MiniIconsRed" },
			vue = { glyph = "", hl = "MiniIconsGreen" },
			ejs = { glyph = "", hl = "MiniIconsOrange" },
			pug = { glyph = "󰚧", hl = "MiniIconsPurple" },
			json = { glyph = "󰘦", hl = "MiniIconsOrange" },
			yaml = { glyph = "", hl = "MiniIconsRed" },
			xml = { glyph = "", hl = "MiniIconsRed" },
			toml = { glyph = "󰰥", hl = "MiniIconsOrange" },
			csv = { glyph = "", hl = "MiniIconsAzure" },
			sql = { glyph = "󰆼", hl = "MiniIconsAzure" },
			graphql = { glyph = "", hl = "MiniIconsRed" },
			markdown = { glyph = "", hl = "MiniIconsOrange" },
			text = { glyph = "󱩼", hl = "MiniIconsPurple" },
			makefile = { glyph = "", hl = "MiniIconsOrange" },
			cmake = { glyph = "", hl = "MiniIconsOrange" },
			dockerfile = { glyph = "󰡨", hl = "MiniIconsAzure" },
			gitignore = { glyph = "", hl = "MiniIconsRed" },
			eslintrc = { glyph = "", hl = "MiniIconsRed" },
			prettierrc = { glyph = "", hl = "MiniIconsRed" },
			babelrc = { glyph = "󰨥", hl = "MiniIconsRed" },
			http = { glyph = "󰭄", hl = "MiniIconsRed" },
			npmrc = { glyph = "", hl = "MiniIconsAzure" },
			h = { glyph = "󰙲", hl = "MiniIconsAzure" },
			hpp = { glyph = "󰙲", hl = "MiniIconsAzure" },
			jade = { glyph = "", hl = "MiniIconsPurple" },
			diff = { glyph = "", hl = "MiniIconsAzure" },
			patch = { glyph = "", hl = "MiniIconsAzure" },
		},
		directory = {
			glyph = "󱃪",
			hl = "MiniIconsAzure",
			[".git"] = { glyph = "", hl = "MiniIconsOrange" },
			["node_modules"] = { glyph = "󰉐", hl = "MiniIconsGreen" },
			["src"] = { glyph = "󰉎", hl = "MiniIconsAzure" },
			["dist"] = { glyph = "󱁽", hl = "MiniIconsPurple" },
			["build"] = { glyph = "󰢬", hl = "MiniIconsOrange" },
			["tests"] = { glyph = "󱧼", hl = "MiniIconsGreen" },
			["docs"] = { glyph = "󰲂", hl = "MiniIconsCyan" },
			["images"] = { glyph = "󰉏", hl = "MiniIconsCyan" },
			["assets"] = { glyph = "󱋣", hl = "MiniIconsOrange" },
			["lsp"] = { glyph = "󱥾", hl = "MiniIconsPurple" },
			["api"] = { glyph = "󰡰", hl = "MiniIconsRed" },
			["public"] = { glyph = "󰉑", hl = "MiniIconsPurple" },
			["static"] = { glyph = "󰉌", hl = "MiniIconsCyan" },
			["components"] = { glyph = "", hl = "MiniIconsRed" },
			["pages"] = { glyph = "󱗖", hl = "MiniIconsGreen" },
			["views"] = { glyph = "", hl = "MiniIconsOrange" },
			["layouts"] = { glyph = "", hl = "MiniIconsCyan" },
			["router"] = { glyph = "󰑩", hl = "MiniIconsOrange" },
			["routes"] = { glyph = "󰑪", hl = "MiniIconsOrange" },
			["routers"] = { glyph = "󰑩", hl = "MiniIconsOrange" },
			["store"] = { glyph = "󱣇", hl = "MiniIconsPurple" },
			["hooks"] = { glyph = "󱧬", hl = "MiniIconsAzure" },
			["utils"] = { glyph = "󰟻", hl = "MiniIconsOrange" },
			["helpers"] = { glyph = "", hl = "MiniIconsOrange" },
			["config"] = { glyph = "", hl = "MiniIconsPurple" },
			["configs"] = { glyph = "", hl = "MiniIconsPurple" },
			["controllers"] = { glyph = "󰊴", hl = "MiniIconsAzure" },
			["handlers"] = { glyph = "", hl = "MiniIconsAzure" },
			["models"] = { glyph = "󰣩", hl = "MiniIconsPurple" },
			["entities"] = { glyph = "", hl = "MiniIconsPurple" },
			["schemas"] = { glyph = "", hl = "MiniIconsPurple" },
			["dto"] = { glyph = "󰗜", hl = "MiniIconsPurple" },
			["services"] = { glyph = "", hl = "MiniIconsAzure" },
			["middleware"] = { glyph = "󰁨", hl = "MiniIconsOrange" },
			["migrations"] = { glyph = "󰁩", hl = "MiniIconsAzure" },
			["alembic"] = { glyph = "󰁪", hl = "MiniIconsAzure" },
			["coverage"] = { glyph = "󰍡", hl = "MiniIconsGreen" },
			[".next"] = { glyph = "", hl = "MiniIconsAzure" },
			[".nuxt"] = { glyph = "󱄆", hl = "MiniIconsGreen" },
			[".vscode"] = { glyph = "󰨞", hl = "MiniIconsAzure" },
			[".idea"] = { glyph = "󰨟", hl = "MiniIconsPurple" },
			["lib"] = { glyph = "", hl = "MiniIconsAzure" },
			["screens"] = { glyph = "󱣴", hl = "MiniIconsAzure" },
			["navigation"] = { glyph = "󰎐", hl = "MiniIconsAzure" },
			["android"] = { glyph = "", hl = "MiniIconsGreen" },
			["ios"] = { glyph = "󰀵", hl = "MiniIconsPurple" },
			["src-tauri"] = { glyph = "", hl = "MiniIconsAzure" },
			["main"] = { glyph = "", hl = "MiniIconsAzure" },
			["renderer"] = { glyph = "󰈸", hl = "MiniIconsAzure" },
			["preload"] = { glyph = "󰨡", hl = "MiniIconsAzure" },
			["cmd"] = { glyph = "󰆍", hl = "MiniIconsAzure" },
			["internal"] = { glyph = "", hl = "MiniIconsAzure" },
			["pkg"] = { glyph = "󰏓", hl = "MiniIconsAzure" },
			["modules"] = { glyph = "󰆩", hl = "MiniIconsAzure" },
			["guards"] = { glyph = "󰅝", hl = "MiniIconsOrange" },
			["interceptors"] = { glyph = "󰁫", hl = "MiniIconsOrange" },
			["decorators"] = { glyph = "󰆪", hl = "MiniIconsPurple" },
			["containers"] = { glyph = "󰆫", hl = "MiniIconsAzure" },
			["webpack"] = { glyph = "", hl = "MiniIconsOrange" },
			["logs"] = { glyph = "󱂅", hl = "MiniIconsGreen" },
		},
		os = {
			unix = { glyph = "󰌽", hl = "MiniIconsAzure" },
			dos = { glyph = "󰖳", hl = "MiniIconsOrange" },
			mac = { glyph = "󰀵", hl = "MiniIconsPurple" },
		},
	})

	mini_icons.mock_nvim_web_devicons()
end

return M
