local status, mini_icons = pcall(require, "mini.icons")
local M = {}

if not status then
	function M.Config()
		vim.notify("mini.icons is not found ...", vim.log.levels.ERROR, { title = "Nvim" })
	end
	return M
end

function M.Config()
	mini_icons.setup({
		style = "glyph",
		default = {
			glyph = "󰈚",
		},
		extension = {
			["d.ts"] = { glyph = "" },
		},
		file = {
			["README.md"] = { glyph = "" },
			["tsconfig.json"] = { glyph = "" },
			["commitlint.config.js"] = { glyph = "󰜘" },
			["tailwind.config.js"] = { glyph = "󱏿" },
			["go.mod"] = { glyph = "" },
			["go.sum"] = { glyph = "󰞆" },
			["init.lua"] = { glyph = "󱤁" },
			["package.json"] = { glyph = "󰏔" },
			["commands.lua"] = { glyph = "󰇄", hl = "MiniIconsRed" },
			["custom.lua"] = { glyph = "󰬎", hl = "MiniIconsRed" },
			["keymaps.lua"] = { glyph = "󰌌", hl = "MiniIconsRed" },
			["www"] = { glyph = "󰇧" },
			["LICENSE"] = { glyph = "" },
			["server.js"] = { glyph = "󰒋" },
			["tags"] = { glyph = "" },
		},
		filetype = {
			c = { glyph = "" },
			cpp = { glyph = "" },
			cs = { glyph = "" },
			python = { glyph = "" },
			javascript = { glyph = "" },
			typescript = { glyph = "" },
			javascriptreact = { glyph = "" },
			typescriptreact = { glyph = "" },
			java = { glyph = "󰬷" },
			go = { glyph = "" },
			rust = { glyph = "" },
			dart = { glyph = "" },
			lua = { glyph = "󱨇", hl = "MiniIconsGreen" },
			vim = { glyph = "" },
			ruby = { glyph = "󰴭" },
			sh = { glyph = "" },
			bash = { glyph = "" },
			zsh = { glyph = "󰬡" },
			fish = { glyph = "󰈺" },
			html = { glyph = "" },
			css = { glyph = "" },
			scss = { glyph = "" },
			less = { glyph = "󰅯" },
			vue = { glyph = "" },
			ejs = { glyph = "" },
			pug = { glyph = "󰚧" },
			json = { glyph = "󰘦" },
			yaml = { glyph = "" },
			xml = { glyph = "" },
			toml = { glyph = "󰰥" },
			csv = { glyph = "" },
			sql = { glyph = "󰆼" },
			graphql = { glyph = "" },
			markdown = { glyph = "" },
			text = { glyph = "󱩼" },
			pdf = { glyph = "󰈦" },
			epub = { glyph = "󰦜" },
			png = { glyph = "󰸭" },
			jpg = { glyph = "󰈥" },
			jpeg = { glyph = "󰈥" },
			gif = { glyph = "󰵸" },
			webp = { glyph = "󰜫" },
			avif = { glyph = "󰬈" },
			ico = { glyph = "󱞈" },
			svg = { glyph = "" },
			mp3 = { glyph = "󰈣" },
			mp4 = { glyph = "󰁧" },
			mov = { glyph = "󰿎" },
			ttf = { glyph = "" },
			woff = { glyph = "" },
			zip = { glyph = "󰛫" },
			out = { glyph = "" },
			class = { glyph = "" },
			so = { glyph = "" },
			dll = { glyph = "" },
			dylib = { glyph = "󰪃" },
			exe = { glyph = "󰨊" },
			bin = { glyph = "" },
			app = { glyph = "" },
			conf = { glyph = "" },
			ini = { glyph = "󰒓" },
			cfg = { glyph = "󰒓" },
			rc = { glyph = "󰒓" },
			properties = { glyph = "" },
			lock = { glyph = "󰦝" },
			lockb = { glyph = "󰦝" },
			test = { glyph = "" },
			spec = { glyph = "" },
			makefile = { glyph = "" },
			cmake = { glyph = "" },
			dockerfile = { glyph = "󰡨" },
			dockerignore = { glyph = "󰡨" },
			gitignore = { glyph = "" },
			eslintrc = { glyph = "" },
			prettierrc = { glyph = "" },
			babelrc = { glyph = "󰨥" },
			dat = { glyph = "󱎔" },
			log = { glyph = "" },
			http = { glyph = "󰭄" },
			npmrc = { glyph = "" },
			snippets = { glyph = "" },
			sqlite = { glyph = "󰆼" },
			bak = { glyph = "󰁯" },
			tmp = { glyph = "" },
			swp = { glyph = "󰓢" },
			h = { glyph = "󰙲" },
			hpp = { glyph = "󰙲" },
			jade = { glyph = "" },
			diff = { glyph = "" },
			patch = { glyph = "" },
		},
		directory = {
			glyph = "󱃪",
			[".git"] = { glyph = "" },
			["node_modules"] = { glyph = "󰉐" },
			["src"] = { glyph = "󰉎" },
			["dist"] = { glyph = "󱁽" },
			["build"] = { glyph = "󰢬" },
			["tests"] = { glyph = "󱧼" },
			["docs"] = { glyph = "󰲂" },
			["images"] = { glyph = "󰉏" },
			["assets"] = { glyph = "󱋣" },
			["lsp"] = { glyph = "󱥾" },
			["api"] = { glyph = "󰡰" },
		},
		os = {
			unix = { glyph = "󰌽" },
			dos = { glyph = "󰖳" },
			mac = { glyph = "󰀵" },
		},
	})

	-- 模拟 nvim-web-devicons 以支持 nvim-tree
	mini_icons.mock_nvim_web_devicons()
end

return M
